[package]
name = "ants"
version = "0.1.0"
authors = ["Mattias Evensson <mattias@evensson.eu>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
tensorflow = "0.13.0"

[dev-dependencies]
matches = "0.1.8"